### ISSUE TITLE
AMS integration broken after installing core-24.3.0

### ISSUE THREAD

**Issue by BrukerJan** [turbokongen/hass-AMS#101] opened 2024-03-14 10:35 UTC
Refering to issue #113275.

I reported the matter as a core bug, but it has been closed with reference to the fact that the bug occurs in the AMS integration and must be reported to the maintainer of that integration.

**Comment by turbokongen** [comment] 2024-03-16 08:09
Duplicate of #100

**Closed by turbokongen** 2024-03-16 08:09 UTC

**Comment by BrukerJan** [comment] 2024-03-18 15:52
Problem solved, at least in my setup - thank you for taking action!
